/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;

/**
 *
 * @author CarlosMacaneta
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        
        form1.setVisible(false);
        form2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        main = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        form1 = new javax.swing.JPanel();
        form1Container = new javax.swing.JPanel();
        backFromForm1ToMain = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        scrollPaneTable1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        nome = new javax.swing.JTextField();
        search = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf3 = new javax.swing.JTextField();
        btnSalvarDados = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        totalRegisted = new javax.swing.JLabel();
        btnRefreshTable1 = new javax.swing.JButton();
        form2 = new javax.swing.JPanel();
        form2Container = new javax.swing.JPanel();
        backFromForm2ToMain1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        nome1 = new javax.swing.JTextField();
        search1 = new javax.swing.JTextField();
        btnSearch1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tf4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf5 = new javax.swing.JTextField();
        btnSalvarDados1 = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();
        cardTablesContainer = new javax.swing.JPanel();
        card1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        card1Table1 = new javax.swing.JTable();
        removerTable1Form2 = new javax.swing.JButton();
        actualizarTable1Form2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        totalRegForm2 = new javax.swing.JLabel();
        card2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        card2Table1 = new javax.swing.JTable();
        removerTable2Form2 = new javax.swing.JButton();
        actualizarTable2Form2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        totalRegcard2Form2 = new javax.swing.JLabel();
        lista1 = new javax.swing.JLabel();
        lista2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1190, 650));
        setResizable(false);

        sideBar.setBackground(new java.awt.Color(0, 18, 50));
        sideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Título");
        sideBar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 220, -1));

        btn1.setBackground(new java.awt.Color(0, 18, 50));
        btn1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("Bt1");
        btn1.setBorder(null);
        btn1.setFocusable(false);
        btn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn1.setMargin(new java.awt.Insets(2, 40, 2, 14));
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn1MouseExited(evt);
            }
        });
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        sideBar.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 220, 32));

        btn2.setBackground(new java.awt.Color(0, 18, 50));
        btn2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("Bt2");
        btn2.setBorder(null);
        btn2.setFocusable(false);
        btn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn2.setMargin(new java.awt.Insets(2, 40, 2, 14));
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn2MouseExited(evt);
            }
        });
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        sideBar.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 220, 32));

        btn3.setBackground(new java.awt.Color(0, 18, 50));
        btn3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("Bt3");
        btn3.setBorder(null);
        btn3.setFocusable(false);
        btn3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn3.setMargin(new java.awt.Insets(2, 40, 2, 14));
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn3MouseExited(evt);
            }
        });
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        sideBar.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 220, 32));

        btnExit.setBackground(new java.awt.Color(0, 18, 50));
        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_exit_20px.png"))); // NOI18N
        btnExit.setText("Sair");
        btnExit.setBorder(null);
        btnExit.setDisabledIcon(null);
        btnExit.setDisabledSelectedIcon(null);
        btnExit.setFocusable(false);
        btnExit.setMargin(new java.awt.Insets(2, 40, 2, 14));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        sideBar.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 220, 32));

        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel3.setText("Carlos Macaneta Jr.");
        main.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel4.setText("CMJ-Programmer");
        main.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        form1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        form1Container.setBackground(new java.awt.Color(255, 255, 255));
        form1Container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backFromForm1ToMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_left_20px_1.png"))); // NOI18N
        backFromForm1ToMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backFromForm1ToMainMouseClicked(evt);
            }
        });
        form1Container.add(backFromForm1ToMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("Nome");
        form1Container.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        form1Container.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 10, 610));

        scrollPaneTable1.setBackground(new java.awt.Color(255, 255, 255));
        scrollPaneTable1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        table1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        scrollPaneTable1.setViewportView(table1);

        form1Container.add(scrollPaneTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 620, 280));

        nome.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        form1Container.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 250, 32));

        search.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Pesquisar"));
        form1Container.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 540, 50));

        btnSearch.setBackground(new java.awt.Color(0, 18, 50));
        btnSearch.setForeground(new java.awt.Color(0, 18, 50));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_search_25px.png"))); // NOI18N
        btnSearch.setFocusable(false);
        btnSearch.setOpaque(false);
        form1Container.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, -1, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setText("jLabel6");
        form1Container.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        tf2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        form1Container.add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 250, 32));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setText("jLabel7");
        form1Container.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        tf3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        form1Container.add(tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 250, 32));

        btnSalvarDados.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnSalvarDados.setText("Salvar dados");
        btnSalvarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarDadosActionPerformed(evt);
            }
        });
        form1Container.add(btnSalvarDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 300, 32));

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        form1Container.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 300, 32));

        btnRemove.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnRemove.setText("Remover");
        btnRemove.setEnabled(false);
        btnRemove.setFocusable(false);
        form1Container.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setText("Total de registados:");
        form1Container.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        totalRegisted.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        totalRegisted.setText("0");
        form1Container.add(totalRegisted, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 190, -1));

        btnRefreshTable1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnRefreshTable1.setText("Actualizar");
        btnRefreshTable1.setFocusable(false);
        form1Container.add(btnRefreshTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, -1, -1));

        form1.add(form1Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 955, 610));

        form2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        form2Container.setBackground(new java.awt.Color(255, 255, 255));
        form2Container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backFromForm2ToMain1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_left_20px_1.png"))); // NOI18N
        backFromForm2ToMain1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backFromForm2ToMain1MouseClicked(evt);
            }
        });
        form2Container.add(backFromForm2ToMain1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setText("Nome");
        form2Container.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        form2Container.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 10, 610));

        nome1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        form2Container.add(nome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 250, 32));

        search1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Pesquisar"));
        form2Container.add(search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 540, 50));

        btnSearch1.setBackground(new java.awt.Color(0, 18, 50));
        btnSearch1.setForeground(new java.awt.Color(0, 18, 50));
        btnSearch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_search_25px.png"))); // NOI18N
        btnSearch1.setFocusable(false);
        btnSearch1.setOpaque(false);
        form2Container.add(btnSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, -1, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setText("jLabel6");
        form2Container.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        tf4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        form2Container.add(tf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 250, 32));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setText("jLabel7");
        form2Container.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        tf5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        form2Container.add(tf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 250, 32));

        btnSalvarDados1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnSalvarDados1.setText("Salvar dados");
        btnSalvarDados1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarDados1ActionPerformed(evt);
            }
        });
        form2Container.add(btnSalvarDados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 300, 32));

        btnCancelar1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnCancelar1.setText("Cancelar");
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });
        form2Container.add(btnCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 300, 32));

        cardTablesContainer.setBackground(new java.awt.Color(255, 255, 255));
        cardTablesContainer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cardTablesContainer.setLayout(new java.awt.CardLayout());

        card1.setBackground(new java.awt.Color(255, 255, 255));

        card1Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        card1Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card1Table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(card1Table1);

        removerTable1Form2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        removerTable1Form2.setText("Remover");
        removerTable1Form2.setEnabled(false);
        removerTable1Form2.setFocusable(false);
        removerTable1Form2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerTable1Form2ActionPerformed(evt);
            }
        });

        actualizarTable1Form2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        actualizarTable1Form2.setText("Actualizar");
        actualizarTable1Form2.setFocusable(false);
        actualizarTable1Form2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarTable1Form2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setText("Total de registados:");

        totalRegForm2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        totalRegForm2.setText("0");

        javax.swing.GroupLayout card1Layout = new javax.swing.GroupLayout(card1);
        card1.setLayout(card1Layout);
        card1Layout.setHorizontalGroup(
            card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(card1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalRegForm2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(actualizarTable1Form2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removerTable1Form2)
                .addContainerGap())
        );
        card1Layout.setVerticalGroup(
            card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(removerTable1Form2)
                        .addComponent(actualizarTable1Form2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(totalRegForm2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cardTablesContainer.add(card1, "card2");

        card2.setBackground(new java.awt.Color(255, 255, 255));

        card2Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        card2Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card2Table1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(card2Table1);

        removerTable2Form2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        removerTable2Form2.setText("Remover");
        removerTable2Form2.setEnabled(false);
        removerTable2Form2.setFocusable(false);
        removerTable2Form2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerTable2Form2ActionPerformed(evt);
            }
        });

        actualizarTable2Form2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        actualizarTable2Form2.setText("Actualizar");
        actualizarTable2Form2.setFocusable(false);
        actualizarTable2Form2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarTable2Form2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setText("Total de registados:");

        totalRegcard2Form2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        totalRegcard2Form2.setText("0");

        javax.swing.GroupLayout card2Layout = new javax.swing.GroupLayout(card2);
        card2.setLayout(card2Layout);
        card2Layout.setHorizontalGroup(
            card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(card2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalRegcard2Form2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(actualizarTable2Form2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removerTable2Form2)
                .addContainerGap())
        );
        card2Layout.setVerticalGroup(
            card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card2Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(removerTable2Form2)
                        .addComponent(actualizarTable2Form2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(totalRegcard2Form2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cardTablesContainer.add(card2, "card2");

        form2Container.add(cardTablesContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 620, 340));

        lista1.setBackground(new java.awt.Color(0, 18, 50));
        lista1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lista1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lista1.setText("Lista 1");
        lista1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lista1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista1MouseClicked(evt);
            }
        });
        form2Container.add(lista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 120, 32));

        lista2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lista2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lista2.setText("Lista 2");
        lista2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lista2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista2MouseClicked(evt);
            }
        });
        form2Container.add(lista2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 120, 32));

        form2.add(form2Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 955, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 235, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(form1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 955, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(form2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 955, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, 1226, Short.MAX_VALUE)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(form1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(form2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    //--------------------side bar------------------\\
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        main.setVisible(false);
        form1.setVisible(true);
        table1.clearSelection();
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        main.setVisible(false);
        form1.setVisible(false);
        form2.setVisible(true);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3ActionPerformed

//----------------------------form 1----------------------------\\
    private void backFromForm1ToMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backFromForm1ToMainMouseClicked
        form1.setVisible(false);
        main.setVisible(true);
        btn1.setBackground(new Color(0,18, 50));
        table1.clearSelection();
    }//GEN-LAST:event_backFromForm1ToMainMouseClicked

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        if (table1.getSelectedRow() != -1) {
            btnRemove.setEnabled(true);
        }
    }//GEN-LAST:event_table1MouseClicked

    private void btn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseEntered
        btn1.setBackground(new Color(255,0, 0));
    }//GEN-LAST:event_btn1MouseEntered

    private void btn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseEntered
        btn2.setBackground(new Color(255,0, 0));
    }//GEN-LAST:event_btn2MouseEntered

    private void btn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseEntered
        btn3.setBackground(new Color(255,0, 0));
    }//GEN-LAST:event_btn3MouseEntered

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setBackground(new Color(255,0, 0));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseExited
        btn1.setBackground(new Color(0,18, 50));
    }//GEN-LAST:event_btn1MouseExited

    private void btn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseExited
        btn2.setBackground(new Color(0,18, 50));
    }//GEN-LAST:event_btn2MouseExited

    private void btn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseExited
        btn3.setBackground(new Color(0,18, 50));
    }//GEN-LAST:event_btn3MouseExited

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSalvarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarDadosActionPerformed
                
    }//GEN-LAST:event_btnSalvarDadosActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        nome.setText(null);
        tf2.setText(null);
        tf3.setText(null);
    }//GEN-LAST:event_btnCancelarActionPerformed

    //----------------------------form 2----------------------------\\
    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        nome1.setText(null);
        tf4.setText(null);
        tf5.setText(null);
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void btnSalvarDados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarDados1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarDados1ActionPerformed

    private void backFromForm2ToMain1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backFromForm2ToMain1MouseClicked
        form2.setVisible(false);
        main.setVisible(true);
        btn2.setBackground(new Color(0,18, 50));
        card1Table1.clearSelection();
    }//GEN-LAST:event_backFromForm2ToMain1MouseClicked

    private void lista1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista1MouseClicked
        card2.setVisible(false);
        card1.setVisible(true);
        lista1.setBackground(new java.awt.Color(0, 18, 50));
        lista2.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_lista1MouseClicked

    private void lista2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista2MouseClicked
        card1.setVisible(false);
        card2.setVisible(true);
        lista1.setBackground(new java.awt.Color(255, 255, 255));
        lista2.setBackground(new java.awt.Color(0, 18, 50));
    }//GEN-LAST:event_lista2MouseClicked

    private void actualizarTable2Form2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarTable2Form2ActionPerformed
        card2Table1.clearSelection();
    }//GEN-LAST:event_actualizarTable2Form2ActionPerformed

    private void actualizarTable1Form2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarTable1Form2ActionPerformed
        card1Table1.clearSelection();
    }//GEN-LAST:event_actualizarTable1Form2ActionPerformed

    private void removerTable1Form2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerTable1Form2ActionPerformed
        removerTable1Form2.setEnabled(false);
    }//GEN-LAST:event_removerTable1Form2ActionPerformed

    private void removerTable2Form2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerTable2Form2ActionPerformed
        removerTable2Form2.setEnabled(true);
    }//GEN-LAST:event_removerTable2Form2ActionPerformed

    private void card1Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card1Table1MouseClicked
        if (card1Table1.getSelectedRow() != -1) {
            removerTable1Form2.setEnabled(true);
        }
    }//GEN-LAST:event_card1Table1MouseClicked

    private void card2Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card2Table1MouseClicked
        if (card2Table1.getSelectedRow() != -1) {
            removerTable2Form2.setEnabled(true);
        }
    }//GEN-LAST:event_card2Table1MouseClicked

    
    //--------------Tables Treatment
    private void addRowTable1() {
        
    } 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarTable1Form2;
    private javax.swing.JButton actualizarTable2Form2;
    private javax.swing.JLabel backFromForm1ToMain;
    private javax.swing.JLabel backFromForm2ToMain1;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRefreshTable1;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSalvarDados;
    private javax.swing.JButton btnSalvarDados1;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JPanel card1;
    private javax.swing.JTable card1Table1;
    private javax.swing.JPanel card2;
    private javax.swing.JTable card2Table1;
    private javax.swing.JPanel cardTablesContainer;
    private javax.swing.JPanel form1;
    private javax.swing.JPanel form1Container;
    private javax.swing.JPanel form2;
    private javax.swing.JPanel form2Container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lista1;
    private javax.swing.JLabel lista2;
    private javax.swing.JPanel main;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField nome1;
    private javax.swing.JButton removerTable1Form2;
    private javax.swing.JButton removerTable2Form2;
    private javax.swing.JScrollPane scrollPaneTable1;
    private javax.swing.JTextField search;
    private javax.swing.JTextField search1;
    private javax.swing.JPanel sideBar;
    private javax.swing.JTable table1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JLabel totalRegForm2;
    private javax.swing.JLabel totalRegcard2Form2;
    private javax.swing.JLabel totalRegisted;
    // End of variables declaration//GEN-END:variables
}
