/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.exame.recorrencia.views;

import com.exame.recorrencia.controllers.AlbumDao;
import com.exame.recorrencia.models.Album;
import com.exame.recorrencia.models.CD;
import com.exame.recorrencia.models.DVD;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CarlosMacaneta
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        
        form1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        main = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        form1 = new javax.swing.JPanel();
        form1Container = new javax.swing.JPanel();
        backFromForm1ToMain = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        scrollPaneTable1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        nomeDoArtista = new javax.swing.JTextField();
        search = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        anoDeLancamento = new javax.swing.JTextField();
        btnSalvarAlbum = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnRemoveAlbum = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        totalAlbuns = new javax.swing.JLabel();
        btnRefreshTable1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        ritmo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        preco = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tipoDeAlbum = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        quantidaDeMusicas = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        resolucao = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1190, 650));
        setResizable(false);

        sideBar.setBackground(new java.awt.Color(0, 18, 50));
        sideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Título");
        sideBar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 220, -1));

        btn1.setBackground(new java.awt.Color(0, 18, 50));
        btn1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("Albuns");
        btn1.setBorder(null);
        btn1.setFocusable(false);
        btn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn1.setMargin(new java.awt.Insets(2, 40, 2, 14));
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn1MouseExited(evt);
            }
        });
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        sideBar.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 220, 32));

        btnExit.setBackground(new java.awt.Color(0, 18, 50));
        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_exit_20px.png"))); // NOI18N
        btnExit.setText("Sair");
        btnExit.setBorder(null);
        btnExit.setDisabledIcon(null);
        btnExit.setDisabledSelectedIcon(null);
        btnExit.setFocusable(false);
        btnExit.setMargin(new java.awt.Insets(2, 40, 2, 14));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        sideBar.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 220, 32));

        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel3.setText("Carlos Macaneta Jr.");
        main.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel4.setText("CMJ-Programmer");
        main.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        form1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        form1Container.setBackground(new java.awt.Color(255, 255, 255));
        form1Container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backFromForm1ToMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_left_20px_1.png"))); // NOI18N
        backFromForm1ToMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backFromForm1ToMainMouseClicked(evt);
            }
        });
        form1Container.add(backFromForm1ToMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("Nome do artista");
        form1Container.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        form1Container.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 10, 610));

        scrollPaneTable1.setBackground(new java.awt.Color(255, 255, 255));
        scrollPaneTable1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        table1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome do artista", "Tituo", "Ano de lancamento", "Ritmo", "Preco", "Quantidade de Musicas", "Resolucao"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        scrollPaneTable1.setViewportView(table1);

        form1Container.add(scrollPaneTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 620, 280));

        nomeDoArtista.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        form1Container.add(nomeDoArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 250, 32));

        search.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Pesquisar"));
        form1Container.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 540, 50));

        btnSearch.setBackground(new java.awt.Color(0, 18, 50));
        btnSearch.setForeground(new java.awt.Color(0, 18, 50));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_search_25px.png"))); // NOI18N
        btnSearch.setFocusable(false);
        btnSearch.setOpaque(false);
        form1Container.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, -1, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setText("Titulo");
        form1Container.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        form1Container.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 250, 32));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setText("Ano de lancamento");
        form1Container.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        anoDeLancamento.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        form1Container.add(anoDeLancamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 250, 32));

        btnSalvarAlbum.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnSalvarAlbum.setText("Salvar dados");
        btnSalvarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlbumActionPerformed(evt);
            }
        });
        form1Container.add(btnSalvarAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 300, 32));

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        form1Container.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 300, 32));

        btnRemoveAlbum.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnRemoveAlbum.setText("Remover");
        btnRemoveAlbum.setEnabled(false);
        btnRemoveAlbum.setFocusable(false);
        btnRemoveAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveAlbumActionPerformed(evt);
            }
        });
        form1Container.add(btnRemoveAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setText("Total de registados:");
        form1Container.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        totalAlbuns.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        totalAlbuns.setText("0");
        form1Container.add(totalAlbuns, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 190, -1));

        btnRefreshTable1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnRefreshTable1.setText("Actualizar");
        btnRefreshTable1.setFocusable(false);
        btnRefreshTable1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshTable1ActionPerformed(evt);
            }
        });
        form1Container.add(btnRefreshTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, -1, -1));

        jLabel13.setText("Ritmo");
        form1Container.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));
        form1Container.add(ritmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 240, 30));

        jLabel14.setText("Preco");
        form1Container.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));
        form1Container.add(preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 260, 30));

        jLabel15.setText("Tipo de Album");
        form1Container.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        tipoDeAlbum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CD", "DVD" }));
        tipoDeAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoDeAlbumActionPerformed(evt);
            }
        });
        form1Container.add(tipoDeAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 170, -1));

        jLabel16.setText("Quantidade de musicas");
        form1Container.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));
        form1Container.add(quantidaDeMusicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 130, 30));

        jLabel17.setText("Resolucao");
        form1Container.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        resolucao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VGA", "HD", "4k" }));
        resolucao.setEnabled(false);
        form1Container.add(resolucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 170, -1));

        form1.add(form1Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 955, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 235, Short.MAX_VALUE)
                    .addComponent(form1, javax.swing.GroupLayout.PREFERRED_SIZE, 955, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, 1226, Short.MAX_VALUE)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(form1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(616, 616, 616)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    //--------------------side bar------------------\\
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        main.setVisible(false);
        form1.setVisible(true);
        table1.clearSelection();
        addRowTable1();
    }//GEN-LAST:event_btn1ActionPerformed

//----------------------------form 1----------------------------\\
    private void backFromForm1ToMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backFromForm1ToMainMouseClicked
        form1.setVisible(false);
        main.setVisible(true);
        btn1.setBackground(new Color(0,18, 50));
        table1.clearSelection();
    }//GEN-LAST:event_backFromForm1ToMainMouseClicked

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        if (table1.getSelectedRow() != -1) {
            AlbumDao dao = new AlbumDao("pu");
            CD cd = null;
            DVD dvd = null;
            btnRemoveAlbum.setEnabled(true);
            
            
            if (dao.findAll().get(table1.getSelectedRow()) instanceof CD){
                quantidaDeMusicas.setEnabled(true);
                resolucao.setEnabled(false);
                
                cd = (CD) dao.findAll().get(table1.getSelectedRow());
                nomeDoArtista.setText(cd.getNomeDoArtista());
                titulo.setText(cd.getTitulo());
                anoDeLancamento.setText(String.valueOf(cd.getAnoDeLancamento()));
                ritmo.setText(cd.getRitmo());
                preco.setText(String.valueOf(cd.getPreco()));
                quantidaDeMusicas.setText(cd.getQuantidadeDeMusicas()+"");
            }
            if (dao.findAll().get(table1.getSelectedRow()) instanceof DVD){
                dvd = (DVD)  dao.findAll().get(table1.getSelectedRow());
                quantidaDeMusicas.setEnabled(!true);
                resolucao.setEnabled(!false);;
                nomeDoArtista.setText(dvd.getNomeDoArtista());
                titulo.setText(dvd.getTitulo());
                anoDeLancamento.setText(String.valueOf(dvd.getAnoDeLancamento()));
                ritmo.setText(dvd.getRitmo());
                preco.setText(String.valueOf(dvd.getPreco()));
                resolucao.setSelectedItem(dvd.getResoucao());
            }
            
        }
    }//GEN-LAST:event_table1MouseClicked

    private void btn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseEntered
        btn1.setBackground(new Color(255,0, 0));
    }//GEN-LAST:event_btn1MouseEntered

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setBackground(new Color(255,0, 0));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseExited
        btn1.setBackground(new Color(0,18, 50));
    }//GEN-LAST:event_btn1MouseExited

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSalvarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlbumActionPerformed
        AlbumDao dao = new AlbumDao("pu");

        if (table1.getSelectedRow() == -1) {
         if(tipoDeAlbum.getSelectedItem().equals("CD")) {

             Album cd = new CD(null, nomeDoArtista.getText(), titulo.getText(), 
                    Integer.parseInt(anoDeLancamento.getText()), ritmo.getText(), Double.parseDouble(preco.getText()),
                    Integer.parseInt(quantidaDeMusicas.getText()));

            try {
                dao.create(cd);
                JOptionPane.showMessageDialog(this, "Album CD salvo");
            } catch(Exception e) {
                System.err.println(e.getLocalizedMessage());
            }
         } else {
             Album cd = new DVD(null, nomeDoArtista.getText(), titulo.getText(), 
                    Integer.parseInt(anoDeLancamento.getText()), ritmo.getText(), Double.parseDouble(preco.getText()),
                    (String) resolucao.getSelectedItem());

            try {
                dao.create(cd);
                JOptionPane.showMessageDialog(this, "Album DVD salvo");
            } catch(Exception e) {
                System.err.println(e.getLocalizedMessage());
            }
         } 
   
        }else {
            
            if (dao.findAll().get(table1.getSelectedRow()) instanceof CD) {
                CD cd = (CD) dao.findAll().get(table1.getSelectedRow());
             cd.setId(cd.getId());
             cd.setNomeDoArtista(nomeDoArtista.getText());
             cd.setTitulo(titulo.getText());
             cd.setAnoDeLancamento(Integer.parseInt(anoDeLancamento.getText()));
             cd.setRitmo(ritmo.getText());
             cd.setPreco(Double.parseDouble(preco.getText()));
             cd.setQuantidadeDeMusicas(Integer.parseInt(quantidaDeMusicas.getText()));
             try {
                 dao.edit(cd);
                 JOptionPane.showMessageDialog(this, "Album CD editado");
             }catch(Exception e) {
                 JOptionPane.showMessageDialog(this, "O tipo de album nao pode ser alterado");
             }
            }
            
            if (dao.findAll().get(table1.getSelectedRow()) instanceof DVD) {
                DVD cd = (DVD) dao.findAll().get(table1.getSelectedRow());
             cd.setId(cd.getId());
             cd.setNomeDoArtista(nomeDoArtista.getText());
             cd.setTitulo(titulo.getText());
             cd.setAnoDeLancamento(Integer.parseInt(anoDeLancamento.getText()));
             cd.setRitmo(ritmo.getText());
             cd.setPreco(Double.parseDouble(preco.getText()));
             cd.setResoucao((String)resolucao.getSelectedItem());
             try {
                 dao.edit(cd);
                 JOptionPane.showMessageDialog(this, "Album DVD editado");
             }catch(Exception e) {
                 JOptionPane.showMessageDialog(this, "O tipo de album nao pode ser alterado");
             }
            }
            
        }
        addRowTable1();
    }//GEN-LAST:event_btnSalvarAlbumActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        nomeDoArtista.setText(null);
        titulo.setText(null);
        anoDeLancamento.setText(null);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tipoDeAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoDeAlbumActionPerformed
        if (tipoDeAlbum.getSelectedItem().equals("CD")) {
            quantidaDeMusicas.setEnabled(true);
            resolucao.setEnabled(false);
        } else {
            resolucao.setEnabled(true);
            quantidaDeMusicas.setEnabled(false);
        }
    }//GEN-LAST:event_tipoDeAlbumActionPerformed

    private void btnRemoveAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveAlbumActionPerformed
        try {
            AlbumDao dao = new AlbumDao("pu");
            Album a = dao.findAll().get(table1.getSelectedRow());
            
            dao.destroy(a.getId());
            JOptionPane.showMessageDialog(this, "Album removido");
            addRowTable1();
        }catch(Exception e) {
            System.err.println(e.getLocalizedMessage());
        }
        
        table1.clearSelection();
    }//GEN-LAST:event_btnRemoveAlbumActionPerformed

    private void btnRefreshTable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshTable1ActionPerformed
        addRowTable1();
    }//GEN-LAST:event_btnRefreshTable1ActionPerformed

    
    //--------------Tables Treatment
    private void addRowTable1() {
        AlbumDao dao = new AlbumDao("pu");
        
        DefaultTableModel modelo = (DefaultTableModel) table1.getModel();
        modelo.setNumRows(0);
        
        @SuppressWarnings("unchecked")
        List<Album> albuns = dao.findAll();
        //sim = receitas;        
       
        if(!albuns.isEmpty()){    
            totalAlbuns.setText(String.valueOf(dao.getCount()));
            
            String tipo = "";
            CD cd = null;
            DVD dvd = null;
            
            for(Album r: albuns) {
                    
                    if (r instanceof CD){
                        tipo = "CD";
                        cd = (CD) r;
                    }
                    if (r instanceof DVD) {
                        tipo = "DVD";
                        dvd = (DVD) r;
                    }
                    
                modelo.addRow(new String[]{
                    String.valueOf(r.getId()),
                    r.getNomeDoArtista(),
                    r.getTitulo(),
                    String.valueOf(r.getAnoDeLancamento()),
                    String.valueOf(r.getRitmo()),
                    String.valueOf(r.getPreco()),
                    tipo,
                    String.valueOf(cd == null ? 0: cd.getQuantidadeDeMusicas()),
                    String.valueOf(dvd == null ? "---": dvd.getResoucao())
                });
                        }
        }
    } 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anoDeLancamento;
    private javax.swing.JLabel backFromForm1ToMain;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRefreshTable1;
    private javax.swing.JButton btnRemoveAlbum;
    private javax.swing.JButton btnSalvarAlbum;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel form1;
    private javax.swing.JPanel form1Container;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel main;
    private javax.swing.JTextField nomeDoArtista;
    private javax.swing.JTextField preco;
    private javax.swing.JTextField quantidaDeMusicas;
    private javax.swing.JComboBox<String> resolucao;
    private javax.swing.JTextField ritmo;
    private javax.swing.JScrollPane scrollPaneTable1;
    private javax.swing.JTextField search;
    private javax.swing.JPanel sideBar;
    private javax.swing.JTable table1;
    private javax.swing.JComboBox<String> tipoDeAlbum;
    private javax.swing.JTextField titulo;
    private javax.swing.JLabel totalAlbuns;
    // End of variables declaration//GEN-END:variables
}
